<a href="https://colab.research.google.com/github/alexsayys/ep1_imagepy/blob/main/p2_algoritmo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# RECURSIVIDADE
# FUNÇÃO FATORIAL
def fatorial(n):
  if n == 0 or n == 1:
    return 1
  else:
    return n * fatorial(n-1)

In [2]:
print(f"4!: {fatorial(4)}")
print(f"3!: {fatorial(3)}")
print(f"2!: {fatorial(2)}")
print(f"0!: {fatorial(0)}")

4!: 24
3!: 6
2!: 2
0!: 1


In [34]:
# FUNÇÃO FIBONACCI
def fibonacci(n):
  if n <= 1:
    return n
  else:
    return fibonacci(n - 1) + fibonacci(n - 2)

In [37]:
print(f"fibonacci(0): {fibonacci(0)}")
print(f"fibonacci(1): {fibonacci(1)}")
print(f"fibonacci(2): {fibonacci(2)}")
print(f"fibonacci(3): {fibonacci(3)}")
print(f"fibonacci(4): {fibonacci(4)}")
print(f"fibonacci(5): {fibonacci(5)}")

fibonacci(0): 0
fibonacci(1): 1
fibonacci(2): 1
fibonacci(3): 2
fibonacci(4): 3
fibonacci(5): 5


In [50]:
# DECIMAL PARA BINÁRIO
def int2bin(n):
  if n < 2:
    return n
  else:
    return n % 2 + 10 * int2bin(n // 2)

In [52]:
print(f"int2bin(45): {int2bin(45)}")
print(f"int2bin(10): {int2bin(10)}")
print(f"int2bin(3): {int2bin(3)}")
print(f"int2bin(2): {int2bin(2)}")

int2bin(45): 101101
int2bin(10): 1010
int2bin(3): 11
int2bin(2): 10


In [56]:
# QUESTÃO P2 2018
def max_rec(n, v):
  if n == 1: return v[0]

  a = max_rec(n - 1, v)
  x = v[n - 1]
  if a > x:
    return a
  return x

In [57]:
print(max_rec(6, [3, 7, 1, 9, 4, 6]))

9


In [16]:
# NDARRAY COM NUMPY
import numpy as np

impares = np.array([n for n in range(1, 16, 2)])
print(impares)

mt = np.zeros((5,5))
print(mt)

m = 1

for i in range(len(mt)):
  for j in range(len(mt)):
    mt[i, j] = m
    m += 1
print(mt)

print(mt[1:4,1:4])


[ 1  3  5  7  9 11 13 15]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]
 [11. 12. 13. 14. 15.]
 [16. 17. 18. 19. 20.]
 [21. 22. 23. 24. 25.]]
[[ 7.  8.  9.]
 [12. 13. 14.]
 [17. 18. 19.]]
